AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./deploy/api.yaml
      StageName: prod
      Variables:
        LambdaFunctionName: !Ref QueryFunction


  QueryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist/function.zip
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 1536
      Timeout: 60
      # Environment:
      #   Variables:
      #     BUCKET: !Ref ImageBucket
      #     URL: !GetAtt ImageBucket.WebsiteURL
      Policies: AmazonEC2ReadOnlyAccess
          # Statement:
          #   - Resource: "*"
          #     Effect: Allow
          #     Action:
          #       - ec2:DescribeImages
          #   - Resource: "*"
          #     Effect: Allow
          #     Action:
          #       - ec2:ec2:DescribeRegions

  QueryFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref QueryFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${Api}/*

# Outputs:
#   BucketWebsiteUrl:
#     Value: !GetAtt ImageBucket.WebsiteURL
#   Bucket:
#     Value: !Ref ImageBucket