---
swagger: 2.0
info:
  title: EcsImageIdQueryApi
paths:
  /:
    get:
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:903779448426:function:${stageVariables.LambdaFunctionName}/invocations
        type: AWS_PROXY
        httpMethod: post
  /{region}:
    get:
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-northeast-1:903779448426:function:${stageVariables.LambdaFunctionName}/invocations
        type: AWS_PROXY
        httpMethod: post
